

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lending
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lending"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: bash -c "while ! nc -z db 5432; do sleep 1; done && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/lending
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: streamlit run app.py
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data: